export const UI_LABELS = {
  COMMON: {
    APP_NAME: "TaskDock",
    TAGLINE: "Dock Your Tasks. Drive Your Progress.",
    CHECKING_AUTH: "Checking credentials...",
    LOADING_SESSION: "Loading session...",
    BACK_TO_DASHBOARD: "Back to Dashboard",
  },
  AUTH: {
    WORKSPACE_ECOSYSTEM: "The Workspace Ecosystem",
    CREATE_WORKSPACE: "Create Workspace",
    WELCOME_BACK: "Welcome Back",
    SIGNUP_SUBTITLE: "Get started with your productivity platform today",
    LOGIN_SUBTITLE: "Sign in to manage and drive your progress",
    TO_LOGIN_LINK: "Already have an account? Log In",
    TO_SIGNUP_LINK: "Need a workspace? Create an account",
    SIGN_UP: "Sign Up",
    LOG_IN: "Log In",
    FIELD_NAME: "Full Name",
    FIELD_EMAIL: "Email Address",
    FIELD_PASSWORD: "Password",
    SUCCESS_SIGNUP: "Account created! Please check your email for verification.",
    ERROR_LOGIN: "Invalid email or password.",
    ERROR_SIGNUP: "Failed to create account.",
    VALIDATION: {
      EMAIL_REQUIRED: "Email is required",
      EMAIL_INVALID: "Invalid email format",
      PASSWORD_MIN: "Password must be at least 6 characters",
      NAME_MIN: "Full name must be at least 2 characters",
    },
  },
  DASHBOARD: {
    TITLE: "TaskDock Dashboard",
    SUBTITLE: "Welcome to your task management workspace.",
    KANBAN_CARD_TITLE: "Kanban Board",
    KANBAN_CARD_DESC: "Manage and track your tasks visually.",
    KANBAN_CARD_FOOTER: "Kanban workflow will be implemented in Phase 4.",
    PROFILE_CARD_TITLE: "User Profile",
    PROFILE_CARD_DESC: "Check your account status and session metadata.",
    PROFILE_CARD_LINK: "View Profile",
  },
  BOARD: {
    TITLE: "Kanban Board",
    SUBTITLE: "Manage, organize, and drag tasks through workflow columns.",
    PLACEHOLDER: "Kanban drag-and-drop workflow will be implemented in Phase 4.",
  },
  PROFILE: {
    TITLE: "User Profile",
    DEFAULT_USER_NAME: "Demo User",
    DEFAULT_USER_EMAIL: "user@example.com",
    STATS_HEADER: "Account Statistics",
    STATS_PLACEHOLDER: "Statistics widgets will be integrated in Phase 4.",
  },
  SIDEBAR: {
    DASHBOARD: "Dashboard",
    KANBAN_BOARD: "Kanban Board",
    PROFILE: "Profile",
  },
  HEADER: {
    DASHBOARD: "Dashboard",
    KANBAN_BOARD: "Kanban Board",
    USER_PROFILE: "User Profile",
    WORKSPACE: "Workspace",
    DEFAULT_USER: "Workspace User",
  },
} as const;
