export const UI_LABELS = {
  COMMON: {
    APP_NAME: "TaskDock",
    TAGLINE: "Dock Your Tasks. Drive Your Progress.",
    CHECKING_AUTH: "Checking credentials...",
    LOADING_SESSION: "Loading session...",
    BACK_TO_DASHBOARD: "Back to Dashboard",
  },
  AUTH: {
    WORKSPACE_ECOSYSTEM: "The Workspace Ecosystem",
    CREATE_WORKSPACE: "Create Workspace",
    WELCOME_BACK: "Welcome Back",
    SIGNUP_SUBTITLE: "Get started with your productivity platform today",
    LOGIN_SUBTITLE: "Sign in to manage and drive your progress",
    TO_LOGIN_LINK: "Already have an account? Log In",
    TO_SIGNUP_LINK: "Need a workspace? Create an account",
    SIGN_UP: "Sign Up",
    LOG_IN: "Log In",
    FIELD_NAME: "Full Name",
    FIELD_EMAIL: "Email Address",
    FIELD_PASSWORD: "Password",
    SUCCESS_SIGNUP: "Account created! Please check your email for verification.",
    ERROR_LOGIN: "Invalid email or password.",
    ERROR_SIGNUP: "Failed to create account.",
    VALIDATION: {
      EMAIL_REQUIRED: "Email is required",
      EMAIL_INVALID: "Invalid email format",
      PASSWORD_MIN: "Password must be at least 6 characters",
      NAME_MIN: "Full name must be at least 2 characters",
    },
  },
  TASK: {
    VALIDATION: {
      TITLE_REQUIRED: "Title is required",
      TITLE_MAX: "Title cannot exceed 100 characters",
      DESC_MAX: "Description cannot exceed 1000 characters",
      DATE_INVALID: "Invalid date format",
    },
    FORM: {
      CREATE_TITLE: "Create New Task",
      EDIT_TITLE: "Edit Task",
      LABEL_TITLE: "Task Title",
      LABEL_DESC: "Description",
      LABEL_PRIORITY: "Priority",
      LABEL_STATUS: "Status",
      LABEL_DUE_DATE: "Due Date",
      PLACEHOLDER_TITLE: "Enter task title...",
      PLACEHOLDER_DESC: "Enter task description...",
      SUBMIT_CREATE: "Create Task",
      SUBMIT_SAVE: "Save Changes",
      CANCEL: "Cancel",
    },
    TOOLBAR: {
      SEARCH_PLACEHOLDER: "Search tasks by title...",
      FILTER_PRIORITY: "All Priorities",
      FILTER_STATUS: "All Statuses",
      SORT_BY: "Sort by",
      SORT_DUE_DATE: "Due Date",
      SORT_CREATED_AT: "Created Date",
      SORT_PRIORITY: "Priority",
      ADD_TASK_BUTTON: "Add Task",
    },
    CARD: {
      NO_DUE_DATE: "No due date",
      EDIT: "Edit",
      DELETE: "Delete",
      CONFIRM_DELETE: "Are you sure you want to delete this task?",
    },
    ERROR: {
      LOAD: "Failed to load tasks.",
      CREATE: "Failed to create task.",
      UPDATE: "Failed to update task.",
      DELETE: "Failed to delete task.",
    },
    STATUS: {
      TO_DO: "To Do",
      IN_PROGRESS: "In Progress",
      COMPLETED: "Completed",
    },
    PRIORITY: {
      LOW: "Low",
      MEDIUM: "Medium",
      HIGH: "High",
    },
    LOADING_TASKS: "Loading workspace tasks...",
    NO_TASKS_FOUND: "No tasks found",
    NO_TASKS_DESC: "Try adjusting your search criteria or add a new task to get started.",
  },
  DASHBOARD: {
    TITLE: "TaskDock Dashboard",
    SUBTITLE: "Welcome to your task management workspace.",
    KANBAN_CARD_TITLE: "Kanban Board",
    KANBAN_CARD_DESC: "Manage and track your tasks visually.",
    KANBAN_CARD_FOOTER: "Kanban workflow will be implemented in Phase 4.",
    PROFILE_CARD_TITLE: "User Profile",
    PROFILE_CARD_DESC: "Check your account status and session metadata.",
    PROFILE_CARD_LINK: "View Profile",
  },
  BOARD: {
    TITLE: "Kanban Board",
    SUBTITLE: "Manage, organize, and drag tasks through workflow columns.",
    PLACEHOLDER: "Kanban drag-and-drop workflow will be implemented in Phase 4.",
  },
  PROFILE: {
    TITLE: "User Profile",
    DEFAULT_USER_NAME: "Demo User",
    DEFAULT_USER_EMAIL: "user@example.com",
    STATS_HEADER: "Account Statistics",
    STATS_PLACEHOLDER: "Statistics widgets will be integrated in Phase 4.",
  },
  SIDEBAR: {
    DASHBOARD: "Dashboard",
    KANBAN_BOARD: "Kanban Board",
    PROFILE: "Profile",
    SETTINGS: "Settings",
    COLLAPSE: "Collapse Sidebar",
    EXPAND: "Expand Sidebar",
  },
  HEADER: {
    DASHBOARD: "Dashboard",
    KANBAN_BOARD: "Kanban Board",
    USER_PROFILE: "User Profile",
    SETTINGS: "Settings",
    WORKSPACE: "Workspace",
    DEFAULT_USER: "Workspace User",
    SIGN_OUT: "Sign Out",
  },
  SETTINGS: {
    TITLE: "Workspace Settings",
    SUBTITLE: "Configure and customize your task management environment.",
    THEME_TITLE: "Theme Customization",
    THEME_DESC: "Select a primary accent color for your workspace buttons, active navigation elements, and badges.",
  },
} as const;
